// <auto-generated />
using API_Labb3.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace API_Labb3.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240428123259_Initial Creation")]
    partial class InitialCreation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Models_Library.Interest", b =>
                {
                    b.Property<int>("InterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("InterestId");

                    b.ToTable("Interests");

                    b.HasData(
                        new
                        {
                            InterestId = 1,
                            Description = "Fotografering är en kreativ hobby och konstform där man fångar bilder med en kamera. Det ger möjlighet att uttrycka sig, dokumentera ögonblick och utforska olika perspektiv. Fotografer kan fokusera på områden som natur, porträtt eller evenemang. Hobbyn kombinerar teknisk kunskap om kameror och bildkomposition med ett öga för estetik, vilket gör det till en uppskattad sysselsättning både professionellt och som fritidsintresse.",
                            Title = "Fotografering"
                        },
                        new
                        {
                            InterestId = 2,
                            Description = "Gaming är en populär hobby där spelare interagerar med digitala spel på olika plattformar som datorer, konsoler och mobila enheter. Det erbjuder en bred variation av genrer, från strategi och äventyr till sport och action, vilket möjliggör både underhållning och mental utmaning. Spelare kan utforska virtuella världar, tävla mot andra, eller samarbeta i team. Gaming förbättrar problemlösningsförmåga, hand-ögon-koordination och sociala färdigheter, och kan även vara en väg till professionell e-sport.",
                            Title = "Gaming"
                        },
                        new
                        {
                            InterestId = 3,
                            Description = "Hästar är fascinerande och ädla djur som engagerar människor världen över, både som husdjur och inom olika ridsporter. De används inom ridskola, dressyr, hoppning och westernridning. Att arbeta med hästar främjar fysisk aktivitet, ansvarskänsla och en djupare förståelse för djur. Många upplever ridning som terapeutiskt och avkopplande. Intresset för hästar kan även leda till yrken som stallskötare, tränare eller veterinär, vilket gör det till ett berikande och mångsidigt intresse.",
                            Title = "Hästar"
                        },
                        new
                        {
                            InterestId = 4,
                            Description = "Läsning är en berikande hobby som öppnar dörrar till olika världar och perspektiv genom böcker. Den erbjuder både underhållning och kunskap, från historiska berättelser till framtida spekulationer. Läsare kan dyka in i skönlitteratur för att fly verkligheten eller utforska facklitteratur för att lära sig nya fakta och färdigheter. Läsning stärker ordförrådet, förbättrar minnet och analytiska förmågor, och ger en lugn stund i en annars hektisk vardag. Det är ett intresse som enkelt kan anpassas till varje livsstil.",
                            Title = "Läsning"
                        },
                        new
                        {
                            InterestId = 5,
                            Description = "Vandring och friluftsliv är populära aktiviteter som ger människor möjlighet att komma närmare naturen och främja fysisk hälsa. Dessa aktiviteter inkluderar allt från lätta promenader i lokala parker till utmanande bergsbestigningar. Vandring erbjuder en unik kombination av motion, äventyr och avkoppling. Många uppskattar möjligheten att andas frisk luft, uppleva vilda landskap och observera djur i deras naturliga miljö. Friluftsliv kan även innebära camping, paddling och fågelskådning, vilket gör det till ett mångsidigt och berikande intresse.",
                            Title = "Vandring och friluftsliv"
                        });
                });

            modelBuilder.Entity("Models_Library.InterestLink", b =>
                {
                    b.Property<int>("InterestLinkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("InterestLinkId"));

                    b.Property<int>("PersonInterestId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("InterestLinkId");

                    b.HasIndex("PersonInterestId");

                    b.ToTable("Interestlinks");

                    b.HasData(
                        new
                        {
                            InterestLinkId = 1,
                            PersonInterestId = 1,
                            Url = "https://digitalfotoforalla.se/fotografering"
                        },
                        new
                        {
                            InterestLinkId = 2,
                            PersonInterestId = 2,
                            Url = "https://gamerant.com/gaming/"
                        },
                        new
                        {
                            InterestLinkId = 3,
                            PersonInterestId = 3,
                            Url = "https://www.friluftsframjandet.se/lat-aventyret-borja/hitta-aventyr/vandring/"
                        },
                        new
                        {
                            InterestLinkId = 4,
                            PersonInterestId = 4,
                            Url = "https://hastsverige.se/om-hasten/"
                        },
                        new
                        {
                            InterestLinkId = 5,
                            PersonInterestId = 5,
                            Url = "https://www.adlibris.com/se"
                        },
                        new
                        {
                            InterestLinkId = 6,
                            PersonInterestId = 6,
                            Url = "https://www.pcgamer.com/news/"
                        },
                        new
                        {
                            InterestLinkId = 7,
                            PersonInterestId = 7,
                            Url = "https://www.reldinadventures.com/tips-om-vandring-och-friluftsliv-for-nyborjaren/"
                        });
                });

            modelBuilder.Entity("Models_Library.Person", b =>
                {
                    b.Property<int>("PersonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PersonId");

                    b.ToTable("Persons");

                    b.HasData(
                        new
                        {
                            PersonId = 1,
                            Name = "Eddie Halling",
                            PhoneNumber = "0704862648"
                        },
                        new
                        {
                            PersonId = 2,
                            Name = "Sara Liljedahl",
                            PhoneNumber = "0704126534"
                        },
                        new
                        {
                            PersonId = 3,
                            Name = "Vincent Johansson",
                            PhoneNumber = "0704734977"
                        });
                });

            modelBuilder.Entity("Models_Library.PersonInterest", b =>
                {
                    b.Property<int>("PersonInterestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PersonInterestId"));

                    b.Property<int>("InterestId")
                        .HasColumnType("int");

                    b.Property<int>("PersonId")
                        .HasColumnType("int");

                    b.HasKey("PersonInterestId");

                    b.HasIndex("InterestId");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonInterests");

                    b.HasData(
                        new
                        {
                            PersonInterestId = 1,
                            InterestId = 1,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 2,
                            InterestId = 2,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 3,
                            InterestId = 5,
                            PersonId = 1
                        },
                        new
                        {
                            PersonInterestId = 4,
                            InterestId = 3,
                            PersonId = 2
                        },
                        new
                        {
                            PersonInterestId = 5,
                            InterestId = 4,
                            PersonId = 2
                        },
                        new
                        {
                            PersonInterestId = 6,
                            InterestId = 2,
                            PersonId = 3
                        },
                        new
                        {
                            PersonInterestId = 7,
                            InterestId = 5,
                            PersonId = 3
                        });
                });

            modelBuilder.Entity("Models_Library.InterestLink", b =>
                {
                    b.HasOne("Models_Library.PersonInterest", "PersonInterest")
                        .WithMany("InterestLinks")
                        .HasForeignKey("PersonInterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PersonInterest");
                });

            modelBuilder.Entity("Models_Library.PersonInterest", b =>
                {
                    b.HasOne("Models_Library.Interest", "Interest")
                        .WithMany("PersonInterests")
                        .HasForeignKey("InterestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Models_Library.Person", "Person")
                        .WithMany("PersonInterests")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Interest");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Models_Library.Interest", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("Models_Library.Person", b =>
                {
                    b.Navigation("PersonInterests");
                });

            modelBuilder.Entity("Models_Library.PersonInterest", b =>
                {
                    b.Navigation("InterestLinks");
                });
#pragma warning restore 612, 618
        }
    }
}
